# .github/workflows/main.yaml
name: main

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.19.x"

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run Tests
        run: go test -cover -p 1 -race -v ./...
