# .github/workflows/release.yaml
name: release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.x"

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "latest"

      - name: Run Tests
        run: go test -p 1 -cover -race -v ./...

  release:
    runs-on: ubuntu-latest
    needs: [test]
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.x"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
